name: zego_express_engine_example
description: Demonstrates how to use the zego_express_engine plugin.
publish_to: "none"

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  zego_express_engine:
    path: ../

  permission_handler: 8.1.2
  shared_preferences: 2.0.6
  url_launcher: 6.0.6
  universal_io: 2.0.4

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - resources/images/
