name: zego_express_engine
summary: Zego RTC SDK for Flutter
description: ZegoExpressEngine Flutter SDK is a flutter plugin wrapper based on ZEGO Express RTC SDK (Native & Web), providing live video and real-time audio/video services.
version: 3.10.0
homepage: https://zego.im

environment:
  sdk: ">=2.12.0 <4.0.0"
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0

flutter:
  plugin:
    platforms:
      android:
        package: im.zego.zego_express_engine
        pluginClass: ZegoExpressEnginePlugin
      ios:
        pluginClass: ZegoExpressEnginePlugin
